application: your-app-id
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
#Endpoings handler: Must be/_ah/spi. Apps send request to /_ah/api, but these are handled at /_ah/spi!!
- url: /_ah/spi/.*
  script: helloworld_api.APPLICATION
  
libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0